validation:
  origin: "test-stream-json"
  schema_path: "config/some_device_scheme.json"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"


udp_server:
  ip: "0.0.0.0"
  port: 9999
  topic: "rtls.events"

broker:
  envelope_version: "1.0"

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  exchange: "rtls"
  exchange_type: "topic"
  queue: "rtls.events"
  routing_key: "rtls.events"

backend:
  api:
    host: "127.0.0.1"
    port: 8000

database:
  dsn: "postgresql://postgres:postgres@localhost:5432/rtls_stream_visualizer"
