validation:
  schemas:
    - name: "ls_1000"
      origin: "ls-1000"
      schema_path: "config/ls_1000_scheme.json"
    - name: "another_scheme"
      origin: "some-device"
      schema_path: "config/some_device_scheme.json"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"


udp_server:
  ip: "0.0.0.0"
  port: 9999
  topic: "rtls.events"
