validation:
  origin: "test-stream-json"
  schema_path: "config/some_device_scheme.json"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"


udp_server:
  ip: "0.0.0.0"
  port: 9999
  topic: "rtls.events"

broker:
  envelope_version: "1.0"
